/****************************************************************************
 > File Name: cpu.cpp
 > Author: Netcan
 > Blog: http://www.netcan666.com/
 > Mail: netcan1996@gmail.com
 > Created Time: 2017-12-03 -- 20:31
 ****************************************************************************/

#include "Cpu.h"

ProcessorStatus::ProcessorStatus(uint8_t value): Negative(this->P), Overflow(this->P),
                                    BrkExecuted(this->P), Decimal(this->P),
                                    IrqDisabled(this->P), Zero(this->P),
                                    Carry(this->P) {
	P = value; // 初值
}

const Operation **CPU::optable = CPU::InitOptable();

const Operation ** CPU::InitOptable() {
	static const Operation op_entity[] = {
			{ 0x69, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0x65, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0x75, OpAddressingMode::ZeroPageX, 2, 4, 0, nullptr },
			{ 0x6D, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0x7D, OpAddressingMode::AbsoluteX, 3, 4, 1, nullptr },
			{ 0x79, OpAddressingMode::AbsoluteY, 3, 4, 1, nullptr },
			{ 0x61, OpAddressingMode::IndexIndirect, 2, 6, 0, nullptr },
			{ 0x71, OpAddressingMode::IndirectIndex, 2, 5, 1, nullptr },
			{ 0x29, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0x25, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0x35, OpAddressingMode::ZeroPageX, 2, 4, 0, nullptr },
			{ 0x2D, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0x3D, OpAddressingMode::AbsoluteX, 3, 4, 1, nullptr },
			{ 0x39, OpAddressingMode::AbsoluteY, 3, 4, 1, nullptr },
			{ 0x21, OpAddressingMode::IndexIndirect, 2, 6, 0, nullptr },
			{ 0x31, OpAddressingMode::IndirectIndex, 2, 5, 1, nullptr },
			{ 0x0A, OpAddressingMode::Accumulator, 1, 2, 0, nullptr },
			{ 0x06, OpAddressingMode::ZeroPage, 2, 5, 0, nullptr },
			{ 0x16, OpAddressingMode::ZeroPageX, 2, 6, 0, nullptr },
			{ 0x0E, OpAddressingMode::Absolute, 3, 6, 0, nullptr },
			{ 0x1E, OpAddressingMode::AbsoluteX, 3, 7, 0, nullptr },
			{ 0x90, OpAddressingMode::Relative, 2, 2, 2, nullptr },
			{ 0xB0, OpAddressingMode::Relative, 2, 2, 2, nullptr },
			{ 0xF0, OpAddressingMode::Relative, 2, 2, 2, nullptr },
			{ 0x24, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0x2C, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0x30, OpAddressingMode::Relative, 2, 2, 2, nullptr },
			{ 0xD0, OpAddressingMode::Relative, 2, 2, 2, nullptr },
			{ 0x10, OpAddressingMode::Relative, 2, 2, 2, nullptr },
			{ 0x00, OpAddressingMode::Implicit, 1, 7, 0, nullptr },
			{ 0x50, OpAddressingMode::Relative, 2, 2, 2, nullptr },
			{ 0x70, OpAddressingMode::Relative, 2, 2, 2, nullptr },
			{ 0x18, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0xD8, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0x58, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0xB8, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0xC9, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0xC5, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0xD5, OpAddressingMode::ZeroPageX, 2, 4, 0, nullptr },
			{ 0xCD, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0xDD, OpAddressingMode::AbsoluteX, 3, 4, 1, nullptr },
			{ 0xD9, OpAddressingMode::AbsoluteY, 3, 4, 1, nullptr },
			{ 0xC1, OpAddressingMode::IndexIndirect, 2, 6, 0, nullptr },
			{ 0xD1, OpAddressingMode::IndirectIndex, 2, 5, 1, nullptr },
			{ 0xE0, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0xE4, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0xEC, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0xC0, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0xC4, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0xCC, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0xC6, OpAddressingMode::ZeroPage, 2, 5, 0, nullptr },
			{ 0xD6, OpAddressingMode::ZeroPageX, 2, 6, 0, nullptr },
			{ 0xCE, OpAddressingMode::Absolute, 3, 6, 0, nullptr },
			{ 0xDE, OpAddressingMode::AbsoluteX, 3, 7, 0, nullptr },
			{ 0xCA, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0x88, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0x49, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0x45, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0x55, OpAddressingMode::ZeroPageX, 2, 4, 0, nullptr },
			{ 0x4D, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0x5D, OpAddressingMode::AbsoluteX, 3, 4, 1, nullptr },
			{ 0x59, OpAddressingMode::AbsoluteY, 3, 4, 1, nullptr },
			{ 0x41, OpAddressingMode::IndexIndirect, 2, 6, 0, nullptr },
			{ 0x51, OpAddressingMode::IndirectIndex, 2, 5, 1, nullptr },
			{ 0xE6, OpAddressingMode::ZeroPage, 2, 5, 0, nullptr },
			{ 0xF6, OpAddressingMode::ZeroPageX, 2, 6, 0, nullptr },
			{ 0xEE, OpAddressingMode::Absolute, 3, 6, 0, nullptr },
			{ 0xFE, OpAddressingMode::AbsoluteX, 3, 7, 0, nullptr },
			{ 0xE8, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0xC8, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0x4C, OpAddressingMode::Absolute, 3, 3, 0, nullptr },
			{ 0x6C, OpAddressingMode::Indirect, 3, 5, 0, nullptr },
			{ 0x20, OpAddressingMode::Absolute, 3, 6, 0, nullptr },
			{ 0xA9, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0xA5, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0xB5, OpAddressingMode::ZeroPageX, 2, 4, 0, nullptr },
			{ 0xAD, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0xBD, OpAddressingMode::AbsoluteX, 3, 4, 1, nullptr },
			{ 0xB9, OpAddressingMode::AbsoluteY, 3, 4, 1, nullptr },
			{ 0xA1, OpAddressingMode::IndexIndirect, 2, 6, 0, nullptr },
			{ 0xB1, OpAddressingMode::IndirectIndex, 2, 5, 1, nullptr },
			{ 0xA2, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0xA6, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0xB6, OpAddressingMode::ZeroPageY, 2, 4, 0, nullptr },
			{ 0xAE, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0xBE, OpAddressingMode::AbsoluteY, 3, 4, 1, nullptr },
			{ 0xA0, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0xA4, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0xB4, OpAddressingMode::ZeroPageX, 2, 4, 0, nullptr },
			{ 0xAC, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0xBC, OpAddressingMode::AbsoluteX, 3, 4, 1, nullptr },
			{ 0x4A, OpAddressingMode::Accumulator, 1, 2, 0, nullptr },
			{ 0x46, OpAddressingMode::ZeroPage, 2, 5, 0, nullptr },
			{ 0x56, OpAddressingMode::ZeroPageX, 2, 6, 0, nullptr },
			{ 0x4E, OpAddressingMode::Absolute, 3, 6, 0, nullptr },
			{ 0x5E, OpAddressingMode::AbsoluteX, 3, 7, 0, nullptr },
			{ 0xEA, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0x09, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0x05, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0x15, OpAddressingMode::ZeroPageX, 2, 4, 0, nullptr },
			{ 0x0D, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0x1D, OpAddressingMode::AbsoluteX, 3, 4, 1, nullptr },
			{ 0x19, OpAddressingMode::AbsoluteY, 3, 4, 1, nullptr },
			{ 0x01, OpAddressingMode::IndexIndirect, 2, 6, 0, nullptr },
			{ 0x11, OpAddressingMode::IndirectIndex, 2, 5, 1, nullptr },
			{ 0x48, OpAddressingMode::Implicit, 1, 3, 0, nullptr },
			{ 0x08, OpAddressingMode::Implicit, 1, 3, 0, nullptr },
			{ 0x68, OpAddressingMode::Implicit, 1, 4, 0, nullptr },
			{ 0x28, OpAddressingMode::Implicit, 1, 4, 0, nullptr },
			{ 0x2A, OpAddressingMode::Accumulator, 1, 2, 0, nullptr },
			{ 0x26, OpAddressingMode::ZeroPage, 2, 5, 0, nullptr },
			{ 0x36, OpAddressingMode::ZeroPageX, 2, 6, 0, nullptr },
			{ 0x2E, OpAddressingMode::Absolute, 3, 6, 0, nullptr },
			{ 0x3E, OpAddressingMode::AbsoluteX, 3, 7, 0, nullptr },
			{ 0x6A, OpAddressingMode::Accumulator, 1, 2, 0, nullptr },
			{ 0x66, OpAddressingMode::ZeroPage, 2, 5, 0, nullptr },
			{ 0x76, OpAddressingMode::ZeroPageX, 2, 6, 0, nullptr },
			{ 0x6E, OpAddressingMode::Absolute, 3, 6, 0, nullptr },
			{ 0x7E, OpAddressingMode::AbsoluteX, 3, 7, 0, nullptr },
			{ 0x40, OpAddressingMode::Implicit, 1, 6, 0, nullptr },
			{ 0x60, OpAddressingMode::Implicit, 1, 6, 0, nullptr },
			{ 0xE9, OpAddressingMode::Immediate, 2, 2, 0, nullptr },
			{ 0xE5, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0xF5, OpAddressingMode::ZeroPageX, 2, 4, 0, nullptr },
			{ 0xED, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0xFD, OpAddressingMode::AbsoluteX, 3, 4, 1, nullptr },
			{ 0xF9, OpAddressingMode::AbsoluteY, 3, 4, 1, nullptr },
			{ 0xE1, OpAddressingMode::IndexIndirect, 2, 6, 0, nullptr },
			{ 0xF1, OpAddressingMode::IndirectIndex, 2, 5, 1, nullptr },
			{ 0x38, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0xF8, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0x78, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0x85, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0x95, OpAddressingMode::ZeroPageX, 2, 4, 0, nullptr },
			{ 0x8D, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0x9D, OpAddressingMode::AbsoluteX, 3, 5, 0, nullptr },
			{ 0x99, OpAddressingMode::AbsoluteY, 3, 5, 0, nullptr },
			{ 0x81, OpAddressingMode::IndexIndirect, 2, 6, 0, nullptr },
			{ 0x91, OpAddressingMode::IndirectIndex, 2, 6, 0, nullptr },
			{ 0x86, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0x96, OpAddressingMode::ZeroPageY, 2, 4, 0, nullptr },
			{ 0x8E, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0x84, OpAddressingMode::ZeroPage, 2, 3, 0, nullptr },
			{ 0x94, OpAddressingMode::ZeroPageX, 2, 4, 0, nullptr },
			{ 0x8C, OpAddressingMode::Absolute, 3, 4, 0, nullptr },
			{ 0xAA, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0xA8, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0xBA, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0x8A, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0x9A, OpAddressingMode::Implicit, 1, 2, 0, nullptr },
			{ 0x98, OpAddressingMode::Implicit, 1, 2, 0, nullptr }
	};


	static_assert(LEN(op_entity) == 151, "instruction count should be 151.");
	static const Operation *optable[0xff];
	for(const auto & op: op_entity) {
		assert(optable[op.code] == nullptr);
		optable[op.code] = &op;
	}
	return optable;
}

uint8_t CPU::Execute() {
	// 执行一条指令，返回执行周期数
	return 0;
}

