/****************************************************************************
 > File Name: cpu.cpp
 > Author: Netcan
 > Blog: http://www.netcan666.com/
 > Mail: netcan1996@gmail.com
 > Created Time: 2017-12-03 -- 20:31
 ****************************************************************************/

#include "Cpu.h"

ProcessorStatus::ProcessorStatus(uint8_t value): Negative(this->P), Overflow(this->P),
                                    BrkExecuted(this->P), Decimal(this->P),
                                    IrqDisabled(this->P), Zero(this->P),
                                    Carry(this->P) {
	P = value; // 初值
}

const Operation **CPU::optable = CPU::InitOptable();

const Operation ** CPU::InitOptable() {
	static const Operation op_entity[] = {
			{OpName::ADC, OpAddressingMode::Immediate, 0x69, 2, 2, 0, nullptr},
			{OpName::ADC, OpAddressingMode::ZeroPage, 0x65, 2, 3, 0, nullptr},
			{OpName::ADC, OpAddressingMode::ZeroPageX, 0x75, 2, 4, 0, nullptr},
			{OpName::ADC, OpAddressingMode::Absolute, 0x6D, 3, 4, 0, nullptr},
			{OpName::ADC, OpAddressingMode::AbsoluteX, 0x7D, 3, 4, 1, nullptr},
			{OpName::ADC, OpAddressingMode::AbsoluteY, 0x79, 3, 4, 1, nullptr},
			{OpName::ADC, OpAddressingMode::IndexIndirect, 0x61, 2, 6, 0, nullptr},
			{OpName::ADC, OpAddressingMode::IndirectIndex, 0x71, 2, 5, 1, nullptr},
			{OpName::AND, OpAddressingMode::Immediate, 0x29, 2, 2, 0, nullptr},
			{OpName::AND, OpAddressingMode::ZeroPage, 0x25, 2, 3, 0, nullptr},
			{OpName::AND, OpAddressingMode::ZeroPageX, 0x35, 2, 4, 0, nullptr},
			{OpName::AND, OpAddressingMode::Absolute, 0x2D, 3, 4, 0, nullptr},
			{OpName::AND, OpAddressingMode::AbsoluteX, 0x3D, 3, 4, 1, nullptr},
			{OpName::AND, OpAddressingMode::AbsoluteY, 0x39, 3, 4, 1, nullptr},
			{OpName::AND, OpAddressingMode::IndexIndirect, 0x21, 2, 6, 0, nullptr},
			{OpName::AND, OpAddressingMode::IndirectIndex, 0x31, 2, 5, 1, nullptr},
			{OpName::ASL, OpAddressingMode::Accumulator, 0x0A, 1, 2, 0, nullptr},
			{OpName::ASL, OpAddressingMode::ZeroPage, 0x06, 2, 5, 0, nullptr},
			{OpName::ASL, OpAddressingMode::ZeroPageX, 0x16, 2, 6, 0, nullptr},
			{OpName::ASL, OpAddressingMode::Absolute, 0x0E, 3, 6, 0, nullptr},
			{OpName::ASL, OpAddressingMode::AbsoluteX, 0x1E, 3, 7, 0, nullptr},
			{OpName::BCC, OpAddressingMode::Relative, 0x90, 2, 2, 2, nullptr},
			{OpName::BCS, OpAddressingMode::Relative, 0xB0, 2, 2, 2, nullptr},
			{OpName::BEQ, OpAddressingMode::Relative, 0xF0, 2, 2, 2, nullptr},
			{OpName::BIT, OpAddressingMode::ZeroPage, 0x24, 2, 3, 0, nullptr},
			{OpName::BIT, OpAddressingMode::Absolute, 0x2C, 3, 4, 0, nullptr},
			{OpName::BMI, OpAddressingMode::Relative, 0x30, 2, 2, 2, nullptr},
			{OpName::BNE, OpAddressingMode::Relative, 0xD0, 2, 2, 2, nullptr},
			{OpName::BPL, OpAddressingMode::Relative, 0x10, 2, 2, 2, nullptr},
			{OpName::BRK, OpAddressingMode::Implicit, 0x00, 1, 7, 0, nullptr},
			{OpName::BVC, OpAddressingMode::Relative, 0x50, 2, 2, 2, nullptr},
			{OpName::BVS, OpAddressingMode::Relative, 0x70, 2, 2, 2, nullptr},
			{OpName::CLC, OpAddressingMode::Implicit, 0x18, 1, 2, 0, nullptr},
			{OpName::CLD, OpAddressingMode::Implicit, 0xD8, 1, 2, 0, nullptr},
			{OpName::CLI, OpAddressingMode::Implicit, 0x58, 1, 2, 0, nullptr},
			{OpName::CLV, OpAddressingMode::Implicit, 0xB8, 1, 2, 0, nullptr},
			{OpName::CMP, OpAddressingMode::Immediate, 0xC9, 2, 2, 0, nullptr},
			{OpName::CMP, OpAddressingMode::ZeroPage, 0xC5, 2, 3, 0, nullptr},
			{OpName::CMP, OpAddressingMode::ZeroPageX, 0xD5, 2, 4, 0, nullptr},
			{OpName::CMP, OpAddressingMode::Absolute, 0xCD, 3, 4, 0, nullptr},
			{OpName::CMP, OpAddressingMode::AbsoluteX, 0xDD, 3, 4, 1, nullptr},
			{OpName::CMP, OpAddressingMode::AbsoluteY, 0xD9, 3, 4, 1, nullptr},
			{OpName::CMP, OpAddressingMode::IndexIndirect, 0xC1, 2, 6, 0, nullptr},
			{OpName::CMP, OpAddressingMode::IndirectIndex, 0xD1, 2, 5, 1, nullptr},
			{OpName::CPX, OpAddressingMode::Immediate, 0xE0, 2, 2, 0, nullptr},
			{OpName::CPX, OpAddressingMode::ZeroPage, 0xE4, 2, 3, 0, nullptr},
			{OpName::CPX, OpAddressingMode::Absolute, 0xEC, 3, 4, 0, nullptr},
			{OpName::CPY, OpAddressingMode::Immediate, 0xC0, 2, 2, 0, nullptr},
			{OpName::CPY, OpAddressingMode::ZeroPage, 0xC4, 2, 3, 0, nullptr},
			{OpName::CPY, OpAddressingMode::Absolute, 0xCC, 3, 4, 0, nullptr},
			{OpName::DEC, OpAddressingMode::ZeroPage, 0xC6, 2, 5, 0, nullptr},
			{OpName::DEC, OpAddressingMode::ZeroPageX, 0xD6, 2, 6, 0, nullptr},
			{OpName::DEC, OpAddressingMode::Absolute, 0xCE, 3, 6, 0, nullptr},
			{OpName::DEC, OpAddressingMode::AbsoluteX, 0xDE, 3, 7, 0, nullptr},
			{OpName::DEX, OpAddressingMode::Implicit, 0xCA, 1, 2, 0, nullptr},
			{OpName::DEY, OpAddressingMode::Implicit, 0x88, 1, 2, 0, nullptr},
			{OpName::EOR, OpAddressingMode::Immediate, 0x49, 2, 2, 0, nullptr},
			{OpName::EOR, OpAddressingMode::ZeroPage, 0x45, 2, 3, 0, nullptr},
			{OpName::EOR, OpAddressingMode::ZeroPageX, 0x55, 2, 4, 0, nullptr},
			{OpName::EOR, OpAddressingMode::Absolute, 0x4D, 3, 4, 0, nullptr},
			{OpName::EOR, OpAddressingMode::AbsoluteX, 0x5D, 3, 4, 1, nullptr},
			{OpName::EOR, OpAddressingMode::AbsoluteY, 0x59, 3, 4, 1, nullptr},
			{OpName::EOR, OpAddressingMode::IndexIndirect, 0x41, 2, 6, 0, nullptr},
			{OpName::EOR, OpAddressingMode::IndirectIndex, 0x51, 2, 5, 1, nullptr},
			{OpName::INC, OpAddressingMode::ZeroPage, 0xE6, 2, 5, 0, nullptr},
			{OpName::INC, OpAddressingMode::ZeroPageX, 0xF6, 2, 6, 0, nullptr},
			{OpName::INC, OpAddressingMode::Absolute, 0xEE, 3, 6, 0, nullptr},
			{OpName::INC, OpAddressingMode::AbsoluteX, 0xFE, 3, 7, 0, nullptr},
			{OpName::INX, OpAddressingMode::Implicit, 0xE8, 1, 2, 0, nullptr},
			{OpName::INY, OpAddressingMode::Implicit, 0xC8, 1, 2, 0, nullptr},
			{OpName::JMP, OpAddressingMode::Absolute, 0x4C, 3, 3, 0, nullptr},
			{OpName::JMP, OpAddressingMode::Indirect, 0x6C, 3, 5, 0, nullptr},
			{OpName::JSR, OpAddressingMode::Absolute, 0x20, 3, 6, 0, nullptr},
			{OpName::LDA, OpAddressingMode::Immediate, 0xA9, 2, 2, 0, nullptr},
			{OpName::LDA, OpAddressingMode::ZeroPage, 0xA5, 2, 3, 0, nullptr},
			{OpName::LDA, OpAddressingMode::ZeroPageX, 0xB5, 2, 4, 0, nullptr},
			{OpName::LDA, OpAddressingMode::Absolute, 0xAD, 3, 4, 0, nullptr},
			{OpName::LDA, OpAddressingMode::AbsoluteX, 0xBD, 3, 4, 1, nullptr},
			{OpName::LDA, OpAddressingMode::AbsoluteY, 0xB9, 3, 4, 1, nullptr},
			{OpName::LDA, OpAddressingMode::IndexIndirect, 0xA1, 2, 6, 0, nullptr},
			{OpName::LDA, OpAddressingMode::IndirectIndex, 0xB1, 2, 5, 1, nullptr},
			{OpName::LDX, OpAddressingMode::Immediate, 0xA2, 2, 2, 0, nullptr},
			{OpName::LDX, OpAddressingMode::ZeroPage, 0xA6, 2, 3, 0, nullptr},
			{OpName::LDX, OpAddressingMode::ZeroPageY, 0xB6, 2, 4, 0, nullptr},
			{OpName::LDX, OpAddressingMode::Absolute, 0xAE, 3, 4, 0, nullptr},
			{OpName::LDX, OpAddressingMode::AbsoluteY, 0xBE, 3, 4, 1, nullptr},
			{OpName::LDY, OpAddressingMode::Immediate, 0xA0, 2, 2, 0, nullptr},
			{OpName::LDY, OpAddressingMode::ZeroPage, 0xA4, 2, 3, 0, nullptr},
			{OpName::LDY, OpAddressingMode::ZeroPageX, 0xB4, 2, 4, 0, nullptr},
			{OpName::LDY, OpAddressingMode::Absolute, 0xAC, 3, 4, 0, nullptr},
			{OpName::LDY, OpAddressingMode::AbsoluteX, 0xBC, 3, 4, 1, nullptr},
			{OpName::LSR, OpAddressingMode::Accumulator, 0x4A, 1, 2, 0, nullptr},
			{OpName::LSR, OpAddressingMode::ZeroPage, 0x46, 2, 5, 0, nullptr},
			{OpName::LSR, OpAddressingMode::ZeroPageX, 0x56, 2, 6, 0, nullptr},
			{OpName::LSR, OpAddressingMode::Absolute, 0x4E, 3, 6, 0, nullptr},
			{OpName::LSR, OpAddressingMode::AbsoluteX, 0x5E, 3, 7, 0, nullptr},
			{OpName::NOP, OpAddressingMode::Implicit, 0xEA, 1, 2, 0, nullptr},
			{OpName::ORA, OpAddressingMode::Immediate, 0x09, 2, 2, 0, nullptr},
			{OpName::ORA, OpAddressingMode::ZeroPage, 0x05, 2, 3, 0, nullptr},
			{OpName::ORA, OpAddressingMode::ZeroPageX, 0x15, 2, 4, 0, nullptr},
			{OpName::ORA, OpAddressingMode::Absolute, 0x0D, 3, 4, 0, nullptr},
			{OpName::ORA, OpAddressingMode::AbsoluteX, 0x1D, 3, 4, 1, nullptr},
			{OpName::ORA, OpAddressingMode::AbsoluteY, 0x19, 3, 4, 1, nullptr},
			{OpName::ORA, OpAddressingMode::IndexIndirect, 0x01, 2, 6, 0, nullptr},
			{OpName::ORA, OpAddressingMode::IndirectIndex, 0x11, 2, 5, 1, nullptr},
			{OpName::PHA, OpAddressingMode::Implicit, 0x48, 1, 3, 0, nullptr},
			{OpName::PHP, OpAddressingMode::Implicit, 0x08, 1, 3, 0, nullptr},
			{OpName::PLA, OpAddressingMode::Implicit, 0x68, 1, 4, 0, nullptr},
			{OpName::PLP, OpAddressingMode::Implicit, 0x28, 1, 4, 0, nullptr},
			{OpName::ROL, OpAddressingMode::Accumulator, 0x2A, 1, 2, 0, nullptr},
			{OpName::ROL, OpAddressingMode::ZeroPage, 0x26, 2, 5, 0, nullptr},
			{OpName::ROL, OpAddressingMode::ZeroPageX, 0x36, 2, 6, 0, nullptr},
			{OpName::ROL, OpAddressingMode::Absolute, 0x2E, 3, 6, 0, nullptr},
			{OpName::ROL, OpAddressingMode::AbsoluteX, 0x3E, 3, 7, 0, nullptr},
			{OpName::ROR, OpAddressingMode::Accumulator, 0x6A, 1, 2, 0, nullptr},
			{OpName::ROR, OpAddressingMode::ZeroPage, 0x66, 2, 5, 0, nullptr},
			{OpName::ROR, OpAddressingMode::ZeroPageX, 0x76, 2, 6, 0, nullptr},
			{OpName::ROR, OpAddressingMode::Absolute, 0x6E, 3, 6, 0, nullptr},
			{OpName::ROR, OpAddressingMode::AbsoluteX, 0x7E, 3, 7, 0, nullptr},
			{OpName::RTI, OpAddressingMode::Implicit, 0x40, 1, 6, 0, nullptr},
			{OpName::RTS, OpAddressingMode::Implicit, 0x60, 1, 6, 0, nullptr},
			{OpName::SBC, OpAddressingMode::Immediate, 0xE9, 2, 2, 0, nullptr},
			{OpName::SBC, OpAddressingMode::ZeroPage, 0xE5, 2, 3, 0, nullptr},
			{OpName::SBC, OpAddressingMode::ZeroPageX, 0xF5, 2, 4, 0, nullptr},
			{OpName::SBC, OpAddressingMode::Absolute, 0xED, 3, 4, 0, nullptr},
			{OpName::SBC, OpAddressingMode::AbsoluteX, 0xFD, 3, 4, 1, nullptr},
			{OpName::SBC, OpAddressingMode::AbsoluteY, 0xF9, 3, 4, 1, nullptr},
			{OpName::SBC, OpAddressingMode::IndexIndirect, 0xE1, 2, 6, 0, nullptr},
			{OpName::SBC, OpAddressingMode::IndirectIndex, 0xF1, 2, 5, 1, nullptr},
			{OpName::SEC, OpAddressingMode::Implicit, 0x38, 1, 2, 0, nullptr},
			{OpName::SED, OpAddressingMode::Implicit, 0xF8, 1, 2, 0, nullptr},
			{OpName::SEI, OpAddressingMode::Implicit, 0x78, 1, 2, 0, nullptr},
			{OpName::STA, OpAddressingMode::ZeroPage, 0x85, 2, 3, 0, nullptr},
			{OpName::STA, OpAddressingMode::ZeroPageX, 0x95, 2, 4, 0, nullptr},
			{OpName::STA, OpAddressingMode::Absolute, 0x8D, 3, 4, 0, nullptr},
			{OpName::STA, OpAddressingMode::AbsoluteX, 0x9D, 3, 5, 0, nullptr},
			{OpName::STA, OpAddressingMode::AbsoluteY, 0x99, 3, 5, 0, nullptr},
			{OpName::STA, OpAddressingMode::IndexIndirect, 0x81, 2, 6, 0, nullptr},
			{OpName::STA, OpAddressingMode::IndirectIndex, 0x91, 2, 6, 0, nullptr},
			{OpName::STX, OpAddressingMode::ZeroPage, 0x86, 2, 3, 0, nullptr},
			{OpName::STX, OpAddressingMode::ZeroPageY, 0x96, 2, 4, 0, nullptr},
			{OpName::STX, OpAddressingMode::Absolute, 0x8E, 3, 4, 0, nullptr},
			{OpName::STY, OpAddressingMode::ZeroPage, 0x84, 2, 3, 0, nullptr},
			{OpName::STY, OpAddressingMode::ZeroPageX, 0x94, 2, 4, 0, nullptr},
			{OpName::STY, OpAddressingMode::Absolute, 0x8C, 3, 4, 0, nullptr},
			{OpName::TAX, OpAddressingMode::Implicit, 0xAA, 1, 2, 0, nullptr},
			{OpName::TAY, OpAddressingMode::Implicit, 0xA8, 1, 2, 0, nullptr},
			{OpName::TSX, OpAddressingMode::Implicit, 0xBA, 1, 2, 0, nullptr},
			{OpName::TXA, OpAddressingMode::Implicit, 0x8A, 1, 2, 0, nullptr},
			{OpName::TXS, OpAddressingMode::Implicit, 0x9A, 1, 2, 0, nullptr},
			{OpName::TYA, OpAddressingMode::Implicit, 0x98, 1, 2, 0, nullptr}
	};
	static_assert(LEN(op_entity) == 151, "instruction count should be 151.");
	static const Operation *optable[0xff];
	for(const auto & op: op_entity) {
		assert(optable[op.code] == nullptr);
		optable[op.code] = &op;
	}
	return optable;
}

